scObj <- withr::with_seed(1, scuttle::mockSCE(ngenes=20000))
scObj <- scuttle::logNormCounts(scObj)
scObj <- scater::runPCA(scObj)
scObj <- withr::with_seed(1, scater::runUMAP(scObj))
seuratObj <- suppressWarnings(Seurat::as.Seurat(scObj, data=NULL))
